api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "brewdog-mup-cart-transform"
type = "function"
uid = "1550101d-6525-c77c-f402-204ef82dc701515e16bd"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.cart-transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
