# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "uwp-bloomreach-consent"
handle = "uwp-bloomreach-consent"
uid = "24a34d65-ba5b-6de1-45d5-f0a321417b73f0d54496"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.actions.render-before"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "consent_text"
# type = "single_line_text_field"
# name = "Consent text"
# description = "Enter some text for the consent box"

[extensions.settings]
[[extensions.settings.fields]]
key = "subscribedToMarketing"
type = "single_line_text_field"
name = "Success message"
description = "Enter some text for the user has successfully subscribed"

[[extensions.settings.fields]]
key = "privacyPolicyURL"
type = "single_line_text_field"
name = "Privacy policy URL"
description = "Enter the URL for the privacy policy"

[[extensions.settings.fields]]
key = "privacyPolicyText"
type = "single_line_text_field"
name = "Privacy policy link text"
description = "Enter the text for the privacy policy link"

[[extensions.settings.fields]]
key = "consentToMarketing"
type = "single_line_text_field"
name = "First line of text"
description = "Enter the text for the first line"

[[extensions.settings.fields]]
key = "consentToMarketing2"
type = "single_line_text_field"
name = "Second line of text"
description = "Enter the text for the second line"
